matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
    - os: linux
      arch: arm64
      dist: bionic
      sudo: false

addons:
  apt:
    packages:
      - libprotobuf-dev
      - protobuf-compiler
language: ruby
rvm:
  - 2.7.0
script:
  - rake spec
